<a href="https://colab.research.google.com/github/pabloviniciuzz/desafios-python-awari/blob/master/Praticando%20-%20Data%20Folia%202022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🎉 **DataFolia 2022** 🎉

### Programação:

- Concentra mas Numpy
- O Py-Tá-On
- Tem Pandas na Folia
- Bloco de Dados
- Regressão é quase amor
- Pra recuperar a energia


# **Concentra mas Numpy 🥳**

In [ ]:
import numpy as np

#### Criando um vetor com os seguintes valores [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]. Chame-o de vetA! 🎨


In [ ]:
vetA = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
vetA

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exiba os 3 primeiros elementos. ⚡

In [ ]:
vetA[:3]

[1, 2, 3]

#### Exiba todos os valores após o quinto elemento. 🐎

In [ ]:
vetA[5:]

[6, 7, 8, 9, 10]

#### Exiba os 3 últimos elementos. 🍏

In [ ]:
vetA[7:]

[8, 9, 10]

#### Exiba os valores de vetA entre o 5 elemento até o penúltimo elemento! ⏰

In [ ]:
vetA[5:-1]

[6, 7, 8, 9]

#### Crie uma matriz 5x5. 🥪

In [ ]:
matriz5 = np.random.randint(1,100, (5,5))

#### Exiba a matriz inteira. ⚾


In [ ]:
print(matriz5)

[[46 54 30 76 29]
 [96 98  9 65 16]
 [68  5 20 51 45]
 [45 22 74 33 49]
 [65 54  1 85 86]]


#### Exiba todos os elementos da coluna 3. 🍎

In [ ]:
print(matriz5[:,2])

[30  9 20 74  1]


#### Exiba todos os elementos da linha 2. 🦑

In [ ]:
print(matriz5[1,:])

[96 98  9 65 16]


#### Exiba todos os elementos das 2 primeiras colunas. 🏀

In [ ]:
# (startindex:endindex:stepsize)

print(matriz5[:,0:2])

[[46 54]
 [96 98]
 [68  5]
 [45 22]
 [65 54]]


#### Exiba todos os elementos das 2 primeiras linhas. ⌛


In [ ]:
print(matriz5[:2,:])

[[46 54 30 76 29]
 [96 98  9 65 16]]


#### Exiba apenas os elementos das 2 últimas linhas e das 4 últimas colunas. 🚃

In [ ]:
print(matriz5[-2:,-4:])

[[22 74 33 49]
 [54  1 85 86]]


#### Crie uma função que receba dois vetores e realize a soma de seus valores. 🐹


In [ ]:
vet1 = np.random.randint(1,10, (2,2))
vet2 = np.random.randint(1,10, (2,2))

In [ ]:
def soma_vetores(vet1, vet2):
  try:
    return np.add(vet1, vet2)
  except:
      print('Erro')
      return np.array([], dtype=int)



In [ ]:
soma_vetores([1,2,3], [4,5,6])

array([5, 7, 9])

#### Generalize a função acima para que ela receba uma string representando a operação a ser executada: '+' ou '-'. ⛔

In [ ]:
def soma_vetores(vet1, vet2, operacao='+'):
  try:
    if operacao == '-':
      return np.subtract(vet1, vet2)
    return np.add(vet1, vet2)
  except:
      print('Erro')
      return np.array([], dtype=int)


In [ ]:
soma_vetores([1,2,3], [4,5,6], '+')

array([5, 7, 9])

In [ ]:
soma_vetores([1,2,3], [4,5,6], '-')

array([-3, -3, -3])

#### Como calcular a média dos valores de uma matriz. 🧞

In [ ]:
matriz5.mean()

48.88

#### Calcule apenas a média das linhas. 🌮

In [ ]:
np.mean(matriz5, axis=1).reshape(5,1)

array([[47. ],
       [56.8],
       [37.8],
       [44.6],
       [58.2]])

#### Calcule apenas a média das colunas. 🩴

In [ ]:
np.mean(matriz5, axis=0)

array([64. , 46.6, 26.8, 62. , 45. ])

# **O Py-Tá-On** 😎

#### Crie uma lista de 3 elementos e calcule a terceira potência de cada elemento

In [ ]:
lista = [2, 3, 4]  
out = np.power(lista, 3) 
print ("Cada elemento da lista elevado a potência 3 é, respectivamente:", out) 

Cada elemento da lista elevado a potência 3 é, respectivamente: [ 8 27 64]


#### Crie uma função que receba uma frase e, para cada palavra, retorne uma lista contendo a palavra original, sua versão minúscula e a quantidade de caracteres. 

> **Ex: 'Eu AMO Carnaval' deverá retornar:**

> ['Eu', 'eu', 2] <br>
> ['AMO', 'amo', 3] <br>
> ['Carnaval', 'carnaval', 8] <br>


In [ ]:
frase = "Eu AMO Carnaval"
array = frase.split()

def funcao():
    print(array[0], array[0].lower(), len(array[0]))
    print(array[1], array[1].lower(), len(array[1]))
    print(array[2], array[2].lower(), len(array[2]))

funcao()



Eu eu 2
AMO amo 3
Carnaval carnaval 8


#### Abaixo você encontra duas listas. Faça com que cada elemento da listaA seja elevado ao elemento correspondente na listaB.

> listaA = [2, 3, 4] <br>
> listaB = [10, 11, 12]

In [ ]:
lista1 = [1,2,3,4,5]
lista2 = [2,3,4,5,6]
lista3 = []

In [ ]:
a = np.array(lista1)
b = np.array(lista2)
print(a ** b)

[    1     8    81  1024 15625]


#### Considere os dois dicionários abaixo. Crie um terceiro dicionário com as chaves do dicionário 1 e os valores do dicionário 2.

> dict1 = {'a':1,'b':2} <br>
> dict2 = {'c':4,'d':5}

In [ ]:
dict1 = {'a':1,'b':2}
dict2 = {'c':4,'d':5}
{a:b for a, b in zip(dict1.keys(), dict2.values())}

{'a': 4, 'b': 5}

# **Tem Pandas na Folia** 🐼


#### Entendendo a situação 

Os sistemas de compartilhamento de bicicletas são um meio de aluguel de bicicletas em que o processo de obtenção de adesão, aluguel e devolução de bicicletas é automatizado por meio de uma rede de quiosques em toda a cidade.

Usando esses sistemas, as pessoas podem alugar uma bicicleta em um local e devolvê-la em um local diferente conforme necessário. Atualmente, existem mais de 500 programas de compartilhamento de bicicletas em todo o mundo.

Os dados gerados por esses sistemas os tornam atraentes para os pesquisadores porque a duração da viagem, local de partida, local de chegada e tempo decorrido são registrados explicitamente. Os sistemas de compartilhamento de bicicletas funcionam, portanto, como uma rede de sensores, que pode ser usada para estudar a mobilidade em uma cidade.

Utilizando o arquivo **bikes.csv**, utilize todos os seus conhecimentos de pandas para retornar informações sobre esse
dataset.


In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
bikes = pd.read_csv('/content/drive/MyDrive/Colab/Data Science/Datasets/bikes.csv')

In [ ]:
bikes.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [ ]:
bikes.describe()

season       holiday    workingday       weather         temp  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.00000   
mean       2.506614      0.028569      0.680875      1.418427     20.23086   
std        1.116174      0.166599      0.466159      0.633839      7.79159   
min        1.000000      0.000000      0.000000      1.000000      0.82000   
25%        2.000000      0.000000      0.000000      1.000000     13.94000   
50%        3.000000      0.000000      1.000000      1.000000     20.50000   
75%        4.000000      0.000000      1.000000      2.000000     26.24000   
max        4.000000      1.000000      1.000000      4.000000     41.00000   

              atemp      humidity     windspeed        casual    registered  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.000000   
mean      23.655084     61.886460     12.799395     36.021955    155.552177   
std        8.474601     19.245033      8.164537     49.960477    151.039033   
min        0.760000      0.000000      0.000000      0.000000      0.000000   
25%       16.665000     47.000000      7.001500      4.000000     36.000000   
50%       24.240000     62.000000     12.998000     17.000000    118.000000   
75%       31.060000     77.000000     16.997900     49.000000    222.000000   
max       45.455000    100.000000     56.996900    367.000000    886.000000   

              count  
count  10886.000000  
mean     191.574132  
std      181.144454  
min        1.000000  
25%       42.000000  
50%      145.000000  
75%      284.000000  
max      977.000000

#### Existem valores nulos?

In [ ]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   datetime    10886 non-null  object 
 1   season      10886 non-null  int64  
 2   holiday     10886 non-null  int64  
 3   workingday  10886 non-null  int64  
 4   weather     10886 non-null  int64  
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64  
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64  
 10  registered  10886 non-null  int64  
 11  count       10886 non-null  int64  
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


#### Exiba uma Series


In [ ]:
bikes['temp']

0         9.84
1         9.02
2         9.02
3         9.84
4         9.84
         ...  
10881    15.58
10882    14.76
10883    13.94
10884    13.94
10885    13.12
Name: temp, Length: 10886, dtype: float64

#### Exiba uma seleção de 3 colunas


In [ ]:
bikes[['datetime', 'temp', 'count']]

datetime   temp  count
0      2011-01-01 00:00:00   9.84     16
1      2011-01-01 01:00:00   9.02     40
2      2011-01-01 02:00:00   9.02     32
3      2011-01-01 03:00:00   9.84     13
4      2011-01-01 04:00:00   9.84      1
...                    ...    ...    ...
10881  2012-12-19 19:00:00  15.58    336
10882  2012-12-19 20:00:00  14.76    241
10883  2012-12-19 21:00:00  13.94    168
10884  2012-12-19 22:00:00  13.94    129
10885  2012-12-19 23:00:00  13.12     88

[10886 rows x 3 columns]

#### Crie uma função lambda que converta a temperatura de Celsius para Fahrenheit

In [ ]:
# Fº = (Cº * 1,8) + 32

bikes_temp = bikes.rename(columns={'temp': 'temp_celsius'})
bikes_temp['temp_fahrenheit'] = bikes_temp['temp_celsius'].apply(lambda x: x * 1.8 + 32)
bikes_temp = bikes_temp[['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp_celsius', 'temp_fahrenheit', 'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count']]

In [ ]:
bikes_temp.sample(5)

datetime  season  holiday  workingday  weather  temp_celsius  \
1861  2011-05-04 11:00:00       2        0           1        1         16.40   
8209  2012-07-03 10:00:00       3        0           1        1         33.62   
8012  2012-06-14 05:00:00       2        0           1        2         24.60   
8960  2012-08-15 17:00:00       3        0           1        1         30.34   
171   2011-01-08 10:00:00       1        0           0        2          7.38   

      temp_fahrenheit   atemp  humidity  windspeed  casual  registered  count  
1861           61.520  20.455        82    22.0028       3          69     72  
8209           92.516  37.120        43    15.0013      56         153    209  
8012           76.280  31.060        56    16.9979       0          40     40  
8960           86.612  34.090        55    19.0012     102         749    851  
171            45.284   9.850        80    11.0014       5          56     61

#### Em season temos os valores 1, 2, 3 e 4 que representam as categorias:

- 1 = spring
- 2 = summer
- 3 = fall
- 4 = winter

**Utilizando o map, altere os valores numéricos para suas respectivas categorias.**

In [ ]:
# criando um dicionário de nomes das estações

season_map = {1: 'spring', 2: 'summer', 3: 'fall', 4: 'winter'}

In [ ]:
# renomeando a coluna 'season' para receber os novos valores

bikes_temp.rename(columns={'season': 'season_encoded'}, inplace=True)

In [ ]:
# inserindo as estações em uma nova coluna 'season_label'

bikes_temp['season_label'] = bikes_temp['season_encoded'].map(season_map)

In [ ]:
# realocando o novo dataset

bikes_temp = bikes_temp[['datetime', 'season_encoded', 'season_label','holiday','workingday','weather',
                         'temp_celsius','temp_fahrenheit','atemp','humidity','windspeed','casual','registered','count']]

# imprimindo

bikes_temp.sample(5)

datetime  season_encoded season_label  holiday  workingday  \
6291   2012-02-18 09:00:00               1       spring        0           0   
10192  2012-11-10 02:00:00               4       winter        0           0   
528    2011-02-05 04:00:00               1       spring        0           0   
7967   2012-06-12 08:00:00               2       summer        0           1   
4085   2011-10-02 06:00:00               4       winter        0           0   

       weather  temp_celsius  temp_fahrenheit   atemp  humidity  windspeed  \
6291         1          9.02           48.236  12.120        80     7.0015   
10192        1         13.12           55.616  17.425        81     0.0000   
528          3          9.02           48.236  11.365        93     8.9981   
7967         2         25.42           77.756  28.030        88    15.0013   
4085         1         13.12           55.616  15.910        81    11.0014   

       casual  registered  count  
6291       22         116    138  
10192       2          42     44  
528         0           8      8  
7967       15         598    613  
4085        2          13     15

#### Demonstre a utilização do LOC.


In [ ]:
bikes_temp.loc[0:5, 'season_encoded':'temp_fahrenheit']

season_encoded season_label  holiday  workingday  weather  temp_celsius  \
0               1       spring        0           0        1          9.84   
1               1       spring        0           0        1          9.02   
2               1       spring        0           0        1          9.02   
3               1       spring        0           0        1          9.84   
4               1       spring        0           0        1          9.84   
5               1       spring        0           0        2          9.84   

   temp_fahrenheit  
0           49.712  
1           48.236  
2           48.236  
3           49.712  
4           49.712  
5           49.712

#### Demonstre a utilização do iLOC


In [ ]:
bikes_temp.iloc[0:5, 1:-6]

season_encoded season_label  holiday  workingday  weather  temp_celsius  \
0               1       spring        0           0        1          9.84   
1               1       spring        0           0        1          9.02   
2               1       spring        0           0        1          9.02   
3               1       spring        0           0        1          9.84   
4               1       spring        0           0        1          9.84   

   temp_fahrenheit  
0           49.712  
1           48.236  
2           48.236  
3           49.712  
4           49.712

#### Explique a diferença entre eles

In [ ]:
# LOC
# df.loc[<linhas>, <colunas>]
# Primeiro argumento são as linhas e o segundo as colunas a serem buscadas.

# ILOC
# Ele seleciona por números inteiros das linhas, arrays ou por slice.

#### Demonstre a utilização do LOC

In [ ]:
bikes_temp.loc[0:3]

datetime  season_encoded season_label  holiday  workingday  \
0  2011-01-01 00:00:00               1       spring        0           0   
1  2011-01-01 01:00:00               1       spring        0           0   
2  2011-01-01 02:00:00               1       spring        0           0   
3  2011-01-01 03:00:00               1       spring        0           0   

   weather  temp_celsius  temp_fahrenheit   atemp  humidity  windspeed  \
0        1          9.84           49.712  14.395        81        0.0   
1        1          9.02           48.236  13.635        80        0.0   
2        1          9.02           48.236  13.635        80        0.0   
3        1          9.84           49.712  14.395        75        0.0   

   casual  registered  count  
0       3          13     16  
1       8          32     40  
2       5          27     32  
3       3          10     13

#### Crie um filtro de sua preferência, armazene-o em uma variável e apresente sua aplicação.

In [ ]:
bikes_tem p[(bikes_temp['casual']+bikes_temp['registered']) != (bikes_temp['count'])]

Empty DataFrame
Columns: [datetime, season_encoded, season_label, holiday, workingday, weather, temp_celsius, temp_fahrenheit, atemp, humidity, windspeed, casual, registered, count]
Index: []

# **Bloco de Dados** 🌍

#### Precisamos escolher a trilha sonora do nosso carnaval! Utilizando o banco de dados **music-store.db**, vamos tentar encontrar as melhores músicas para os nossos convidados.

In [ ]:
import sqlite3

In [ ]:
db = sqlite3.connect('/content/drive/MyDrive/Colab/Data Science/Datasets/music-store.db')
df = db.cursor()

df.execute("CREATE TABLE")

In [ ]:
db

#### Qual artista possui mais albuns?

#### Existem clientes de quantos países?

#### Quantos clientes são brasileiros?

#### Qual genero possui mais músicas?


#### Qual genero possui mais albuns?

#### Exiba os 5 clientes que mais fizeram pedidos.

#### Qual é o valor da maior compra?


#### Quais o email dos 10 clientes que mais gastaram na loja?

#### Qual o valor médio de cada compra?


#### Quantas compras estão acima da média?

#### Vamos fazer uma playlist com as 12 músicas mais vendidas! 

- Quais foram elas? 
- Quais os generos e os artistas?